//! HTTP/3 packet-driven server engine based on pure quinn-proto state machine (RFC 9114).
//!
//! Operates in a pure packet-in / packet-out manner without owning OS sockets,
//! matching `velda-transport`'s `(listener_id, socket, Datagram)` handler model with zero I/O on hot paths.

use std::collections::{HashMap, HashSet};
use std::net::{IpAddr, SocketAddr};
use std::sync::Arc;
use std::time::Instant;

use bytes::{Bytes, BytesMut};
use quinn_proto::{
    Connection, ConnectionHandle, Dir, Endpoint, EndpointConfig, Event, ServerConfig, StreamEvent,
    StreamId,
};
use velda_core::{Body, L7Request, L7Response};

use crate::config::Http3Config;
use crate::error::Http3Error;
use crate::frame::{
    Http3Frame, decode_frame, encode_frame, encode_varint, error_code, settings_id, stream_type,
};
use crate::qpack::decode_qpack;

/// An outgoing UDP packet generated by the HTTP/3 state machine.
#[derive(Debug, Clone)]
pub struct OutgoingDatagram {
    /// Destination remote address.
    pub peer: SocketAddr,
    /// Packet payload.
    pub payload: Bytes,
}

/// An incoming HTTP/3 request ready for application processing.
#[derive(Debug)]
pub struct Http3RequestEvent {
    /// Internal connection handle.
    pub handle: ConnectionHandle,
    /// QUIC bidirectional stream identifier.
    pub stream_id: StreamId,
    /// Parsed L7 request.
    pub request: L7Request,
}

/// High-performance, packet-driven HTTP/3 server engine.
pub struct Http3Engine {
    endpoint: Endpoint,
    connections: HashMap<ConnectionHandle, Connection>,
    control_streams: HashSet<ConnectionHandle>,
    stream_buffers: HashMap<(ConnectionHandle, StreamId), BytesMut>,
    stream_requests: HashMap<(ConnectionHandle, StreamId), L7Request>,
    config: Http3Config,
    transmit_buf: Vec<u8>,
}

impl std::fmt::Debug for Http3Engine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Http3Engine")
            .field("connections", &self.connections.len())
            .field("active_stream_buffers", &self.stream_buffers.len())
            .field("active_requests", &self.stream_requests.len())
            .finish()
    }
}

impl Http3Engine {
    /// Creates a new [`Http3Engine`] initialized with the given server configuration
    /// and auto-detected hardware-scaled [`Http3Config`].
    pub fn new(server_config: Arc<ServerConfig>) -> Self {
        Self::new_with_config(server_config, Http3Config::auto())
    }

    /// Creates a new [`Http3Engine`] with an explicit [`Http3Config`].
    pub fn new_with_config(server_config: Arc<ServerConfig>, config: Http3Config) -> Self {
        let endpoint_config = Arc::new(EndpointConfig::default());
        let endpoint = Endpoint::new(endpoint_config, Some(server_config), false, None);
        Self {
            endpoint,
            connections: HashMap::new(),
            control_streams: HashSet::new(),
            stream_buffers: HashMap::new(),
            stream_requests: HashMap::new(),
            config,
            transmit_buf: Vec::with_capacity(65535),
        }
    }

    /// Ingests an incoming UDP datagram payload, advances the QUIC state machine,
    /// and returns any outgoing UDP packets and complete HTTP/3 requests.
    pub fn handle_datagram(
        &mut self,
        now: Instant,
        remote: SocketAddr,
        local_ip: Option<IpAddr>,
        data: &[u8],
    ) -> (Vec<OutgoingDatagram>, Vec<Http3RequestEvent>) {
        let mut outgoing = Vec::new();
        let mut ready_requests = Vec::new();

        let mut resp_buf = Vec::new();
        let bytes_mut = BytesMut::from(data);

        // 1. Ingest datagram into endpoint
        let event = self
            .endpoint
            .handle(now, remote, local_ip, None, bytes_mut, &mut resp_buf);

        if !resp_buf.is_empty() {
            outgoing.push(OutgoingDatagram {
                peer: remote,
                payload: Bytes::from(resp_buf),
            });
        }

        // 2. Handle connection events
        if let Some(event) = event {
            match event {
                quinn_proto::DatagramEvent::NewConnection(incoming) => {
                    let mut accept_resp = Vec::new();
                    if let Ok((handle, conn)) =
                        self.endpoint.accept(incoming, now, &mut accept_resp, None)
                    {
                        if !accept_resp.is_empty() {
                            outgoing.push(OutgoingDatagram {
                                peer: remote,
                                payload: Bytes::from(accept_resp),
                            });
                        }
                        self.connections.insert(handle, conn);
                    }
                }
                quinn_proto::DatagramEvent::ConnectionEvent(handle, ev) => {
                    if let Some(conn) = self.connections.get_mut(&handle) {
                        conn.handle_event(ev);
                    }
                }
                quinn_proto::DatagramEvent::Response(transmit) => {
                    if transmit.size > 0 {
                        outgoing.push(OutgoingDatagram {
                            peer: transmit.destination,
                            payload: Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]),
                        });
                    }
                }
            }
        }

        // 3. Poll connection events & read streams across connections
        let mut closed_handles = Vec::new();

        for (&handle, conn) in self.connections.iter_mut() {
            // RFC 9114 Section 6.2.1: As soon as the QUIC handshake completes, open the
            // server unidirectional Control Stream and transmit the mandatory SETTINGS frame.
            if !conn.is_handshaking()
                && !self.control_streams.contains(&handle)
                && let Some(ctrl_stream_id) = conn.streams().open(Dir::Uni)
            {
                let mut ctrl_buf = BytesMut::new();
                // Stream Type 0x00 = Control Stream
                encode_varint(stream_type::CONTROL, &mut ctrl_buf);
                // Mandatory first frame: SETTINGS (Type 0x04)
                let settings = vec![
                    (
                        settings_id::QPACK_MAX_TABLE_CAPACITY,
                        self.config.max_qpack_table_capacity as u64,
                    ),
                    (
                        settings_id::MAX_FIELD_SECTION_SIZE,
                        self.config.max_header_size as u64,
                    ),
                    (settings_id::QPACK_BLOCKED_STREAMS, 0),
                ];
                encode_frame(&Http3Frame::Settings(settings), &mut ctrl_buf);
                let _ = conn.send_stream(ctrl_stream_id).write(&ctrl_buf);
                self.control_streams.insert(handle);
            }

            // Drain outgoing transmits for this connection
            self.transmit_buf.clear();
            while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
                if transmit.size > 0 {
                    let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                    outgoing.push(OutgoingDatagram {
                        peer: transmit.destination,
                        payload: packet,
                    });
                }
                self.transmit_buf.clear();
            }

            // Drain connection events
            while let Some(event) = conn.poll() {
                match event {
                    Event::Stream(StreamEvent::Opened { dir }) => {
                        while let Some(id) = conn.streams().accept(dir) {
                            if id.dir() == Dir::Bi {
                                Self::process_readable_stream(
                                    handle,
                                    id,
                                    conn,
                                    &mut self.stream_buffers,
                                    &mut self.stream_requests,
                                    &mut ready_requests,
                                    self.config.max_body_size,
                                );
                            }
                        }
                    }
                    Event::Stream(StreamEvent::Readable { id }) => {
                        if id.dir() == Dir::Uni {
                            if let Ok(mut chunks) = conn.recv_stream(id).read(true) {
                                while let Some(_chunk) = chunks.next(65535).ok().flatten() {}
                            }
                        } else {
                            Self::process_readable_stream(
                                handle,
                                id,
                                conn,
                                &mut self.stream_buffers,
                                &mut self.stream_requests,
                                &mut ready_requests,
                                self.config.max_body_size,
                            );
                        }
                    }
                    Event::Stream(StreamEvent::Finished { .. }) => {
                        // Finished signals that our outgoing send stream was ACKed by client.
                    }
                    Event::Stream(StreamEvent::Stopped { id, .. }) => {
                        self.stream_buffers.remove(&(handle, id));
                        self.stream_requests.remove(&(handle, id));
                    }
                    Event::ConnectionLost { .. } => {
                        closed_handles.push(handle);
                    }
                    _ => {}
                }
            }

            // Drain outgoing transmits generated during event processing
            self.transmit_buf.clear();
            while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
                if transmit.size > 0 {
                    let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                    outgoing.push(OutgoingDatagram {
                        peer: transmit.destination,
                        payload: packet,
                    });
                }
                self.transmit_buf.clear();
            }
        }

        // Clean up closed connections and all associated stream state
        for handle in closed_handles {
            self.connections.remove(&handle);
            self.control_streams.remove(&handle);
            self.stream_buffers.retain(|(h, _), _| *h != handle);
            self.stream_requests.retain(|(h, _), _| *h != handle);
        }

        (outgoing, ready_requests)
    }

    /// Reads incoming stream chunks, decodes HTTP/3 frames, and emits complete requests.
    fn process_readable_stream(
        handle: ConnectionHandle,
        id: StreamId,
        conn: &mut Connection,
        stream_buffers: &mut HashMap<(ConnectionHandle, StreamId), BytesMut>,
        stream_requests: &mut HashMap<(ConnectionHandle, StreamId), L7Request>,
        ready_requests: &mut Vec<Http3RequestEvent>,
        max_body_size: usize,
    ) {
        let buf = stream_buffers.entry((handle, id)).or_default();
        let mut stream_finished = false;
        let mut payload_too_large = false;

        if let Ok(mut chunks) = conn.recv_stream(id).read(true) {
            loop {
                match chunks.next(65535) {
                    Ok(Some(chunk)) => {
                        if buf.len() + chunk.bytes.len() > max_body_size + 65536 {
                            payload_too_large = true;
                            break;
                        }
                        buf.extend_from_slice(&chunk.bytes);
                    }
                    Ok(None) => {
                        stream_finished = true;
                        break;
                    }
                    Err(quinn_proto::ReadError::Blocked) => {
                        break;
                    }
                    Err(quinn_proto::ReadError::Reset(_)) => {
                        stream_buffers.remove(&(handle, id));
                        stream_requests.remove(&(handle, id));
                        return;
                    }
                }
            }
            let _ = chunks.finalize();
        }

        if payload_too_large {
            let _ = conn.recv_stream(id).stop(quinn_proto::VarInt::from_u32(
                error_code::H3_MESSAGE_ERROR as u32,
            ));
            stream_buffers.remove(&(handle, id));
            stream_requests.remove(&(handle, id));
            return;
        }

        // Try decoding HTTP/3 frames
        loop {
            match decode_frame(buf) {
                Ok(Some(frame)) => match frame {
                    Http3Frame::Headers(payload) => match decode_qpack(&payload) {
                        Ok(decoded) => {
                            let req = L7Request::new(
                                decoded.method.unwrap_or(http::Method::GET),
                                decoded.uri.unwrap_or_else(|| http::Uri::from_static("/")),
                                http::Version::HTTP_3,
                                decoded.headers,
                                Body::Empty,
                            );
                            stream_requests.insert((handle, id), req);
                        }
                        Err(e) => {
                            tracing::warn!(error = %e, "Failed to decode QPACK headers");
                            let _ = conn.recv_stream(id).stop(quinn_proto::VarInt::from_u32(
                                error_code::H3_FRAME_ERROR as u32,
                            ));
                            stream_buffers.remove(&(handle, id));
                            stream_requests.remove(&(handle, id));
                            return;
                        }
                    },
                    Http3Frame::Data(payload) => {
                        if let Some(req) = stream_requests.get_mut(&(handle, id)) {
                            match req.body {
                                Body::Empty => {
                                    req.body = Body::Bytes(payload);
                                }
                                Body::Bytes(ref existing) => {
                                    let mut merged =
                                        BytesMut::with_capacity(existing.len() + payload.len());
                                    merged.extend_from_slice(existing);
                                    merged.extend_from_slice(&payload);
                                    req.body = Body::Bytes(merged.freeze());
                                }
                            }
                        }
                    }
                    _ => {}
                },
                Ok(None) => break,
                Err(e) => {
                    tracing::warn!(error = %e, "Malformed HTTP/3 frame on stream");
                    let _ = conn.recv_stream(id).stop(quinn_proto::VarInt::from_u32(
                        error_code::H3_FRAME_ERROR as u32,
                    ));
                    stream_buffers.remove(&(handle, id));
                    stream_requests.remove(&(handle, id));
                    return;
                }
            }
        }

        // Emit request ONLY once the downstream client has finished transmitting (FIN reached)
        if stream_finished {
            stream_buffers.remove(&(handle, id));
            if let Some(req) = stream_requests.remove(&(handle, id)) {
                ready_requests.push(Http3RequestEvent {
                    handle,
                    stream_id: id,
                    request: req,
                });
            }
        }
    }

    /// Serializes an [`L7Response`] into HTTP/3 frames and queues them on the specified stream.
    ///
    /// Delegates to [`crate::server::response::send_response`].
    pub fn send_response(
        &mut self,
        now: Instant,
        handle: ConnectionHandle,
        stream_id: StreamId,
        response: &L7Response,
    ) -> Result<Vec<OutgoingDatagram>, Http3Error> {
        let conn = self
            .connections
            .get_mut(&handle)
            .ok_or_else(|| Http3Error::H3("Connection not found".into()))?;

        crate::server::response::send_response(
            conn,
            stream_id,
            response,
            &mut self.transmit_buf,
            now,
        )
    }

    /// Returns the number of currently active connections.
    #[inline]
    pub fn connection_count(&self) -> usize {
        self.connections.len()
    }

    /// Returns the number of active stream buffers.
    #[inline]
    pub fn active_stream_count(&self) -> usize {
        self.stream_buffers.len()
    }
}
