[package]
name = "velda-http1"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
velda-core = { path = "../velda-core" }
velda-tls = { path = "../velda-tls" }
tokio = { version = "1.43", features = ["io-util", "sync", "macros", "rt", "net"] }
bytes = "1.10"
http = "1.2"
httparse = "1.10"
itoa = "1.0"
thiserror = "2.0"
tracing = "0.1"
memchr = "2.7"

[dev-dependencies]
tokio = { version = "1.43", features = ["full"] }

[[bench]]
name = "single_thread_bench"
harness = false

[[bench]]
name = "multi_thread_bench"
harness = false

[[bench]]
name = "adversarial_bench"
harness = false

[[bench]]
name = "memory_leak_bench"
harness = false
