[package]
name = "velda-http1"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
velda-core = { path = "../velda-core" }
tokio = { version = "1.43", features = ["io-util", "sync", "macros", "rt", "net"] }
bytes = "1.10"
http = "1.2"
httparse = "1.10"
thiserror = "2.0"
tracing = "0.1"

[dev-dependencies]
tokio = { version = "1.43", features = ["full"] }
