[workspace]
resolver = "2"
members = [
    "crates/velda-core",
    "crates/velda-sync",
    "crates/velda-transport",
    "crates/velda-tls",
    "crates/velda-http1",
    "crates/velda-http2",
    "crates/velda-http3",
    "crates/velda-grpc",
    "crates/velda-router",
    "crates/velda-plugin",
    "crates/velda-discovery",
    "crates/velda-upstream",
    "crates/velda-lb",
    "crates/velda-connection-pool",
    "crates/velda-observability",
    "crates/velda-edge",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "Apache-2.0"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.bench]
opt-level = 3
lto = "fat"
codegen-units = 1
debug = false
