//! Packet-driven Layer 7 gRPC server state machine over UDP (RFC 9000 QUIC transport).
//!
//! Operates in a pure packet-in / packet-out model matching `velda-transport`'s
//! `(listener_id, socket, Datagram)` pipeline with zero OS syscalls on the serving path.

use std::collections::{HashMap, HashSet};
use std::net::{IpAddr, SocketAddr};
use std::sync::Arc;
use std::time::Instant;

use bytes::{Bytes, BytesMut};
use quinn_proto::{
    Connection, ConnectionHandle, Dir, Endpoint, EndpointConfig, Event, ServerConfig, StreamEvent,
    StreamId,
};
use velda_core::{Body, L7Request, L7Response};

use crate::config::GrpcConfig;
use crate::error::GrpcError;
use crate::status::GrpcStatus;
use crate::udp::wire::{
    UdpFrame, decode_qpack_headers, decode_udp_frame, encode_qpack_response, encode_udp_frame,
    encode_varint,
};

/// An outgoing UDP packet generated by the gRPC UDP state machine.
#[derive(Debug, Clone)]
pub struct OutgoingDatagram {
    /// Remote destination address.
    pub peer: SocketAddr,
    /// UDP payload bytes.
    pub payload: Bytes,
}

/// An incoming gRPC request ready for routing and execution.
#[derive(Debug)]
pub struct GrpcUdpRequestEvent {
    /// Active connection handle.
    pub handle: ConnectionHandle,
    /// QUIC bidirectional stream identifier.
    pub stream_id: StreamId,
    /// Parsed L7 request representation.
    pub request: L7Request,
}

/// Packet-driven Layer 7 gRPC engine over UDP.
pub struct GrpcUdpEngine {
    endpoint: Endpoint,
    connections: HashMap<ConnectionHandle, Connection>,
    control_streams: HashSet<ConnectionHandle>,
    stream_buffers: HashMap<(ConnectionHandle, StreamId), BytesMut>,
    stream_requests: HashMap<(ConnectionHandle, StreamId), L7Request>,
    config: GrpcConfig,
    transmit_buf: Vec<u8>,
}

impl std::fmt::Debug for GrpcUdpEngine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GrpcUdpEngine")
            .field("connections", &self.connections.len())
            .field("active_stream_buffers", &self.stream_buffers.len())
            .field("active_requests", &self.stream_requests.len())
            .finish()
    }
}

impl GrpcUdpEngine {
    /// Creates a new [`GrpcUdpEngine`] with the given server configuration and gRPC parameters.
    pub fn new(server_config: Arc<ServerConfig>, config: GrpcConfig) -> Self {
        let endpoint_config = Arc::new(EndpointConfig::default());
        let endpoint = Endpoint::new(endpoint_config, Some(server_config), false, None);
        Self {
            endpoint,
            connections: HashMap::new(),
            control_streams: HashSet::new(),
            stream_buffers: HashMap::new(),
            stream_requests: HashMap::new(),
            config,
            transmit_buf: Vec::with_capacity(65535),
        }
    }

    /// Ingests an incoming UDP datagram payload, advances the QUIC transport state machine,
    /// and returns outgoing UDP packets alongside decoded gRPC request events.
    pub fn handle_datagram(
        &mut self,
        now: Instant,
        remote: SocketAddr,
        local_ip: Option<IpAddr>,
        data: &[u8],
    ) -> (Vec<OutgoingDatagram>, Vec<GrpcUdpRequestEvent>) {
        let mut outgoing = Vec::new();
        let mut ready_requests = Vec::new();

        let mut resp_buf = Vec::new();
        let bytes_mut = BytesMut::from(data);

        // 1. Ingest datagram into endpoint
        let event = self
            .endpoint
            .handle(now, remote, local_ip, None, bytes_mut, &mut resp_buf);

        if !resp_buf.is_empty() {
            outgoing.push(OutgoingDatagram {
                peer: remote,
                payload: Bytes::from(resp_buf),
            });
        }

        // 2. Handle connection events
        if let Some(event) = event {
            match event {
                quinn_proto::DatagramEvent::NewConnection(incoming) => {
                    let mut accept_resp = Vec::new();
                    if let Ok((handle, conn)) =
                        self.endpoint.accept(incoming, now, &mut accept_resp, None)
                    {
                        if !accept_resp.is_empty() {
                            outgoing.push(OutgoingDatagram {
                                peer: remote,
                                payload: Bytes::from(accept_resp),
                            });
                        }
                        self.connections.insert(handle, conn);
                    }
                }
                quinn_proto::DatagramEvent::ConnectionEvent(handle, ev) => {
                    if let Some(conn) = self.connections.get_mut(&handle) {
                        conn.handle_event(ev);
                    }
                }
                quinn_proto::DatagramEvent::Response(transmit) => {
                    if transmit.size > 0 {
                        outgoing.push(OutgoingDatagram {
                            peer: transmit.destination,
                            payload: Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]),
                        });
                    }
                }
            }
        }

        // 3. Poll connection events & read streams across connections
        let mut closed_handles = Vec::new();

        for (&handle, conn) in self.connections.iter_mut() {
            // Send SETTINGS on control stream once handshake completes
            if !conn.is_handshaking()
                && !self.control_streams.contains(&handle)
                && let Some(ctrl_stream_id) = conn.streams().open(Dir::Uni)
            {
                let mut ctrl_buf = BytesMut::new();
                // Stream Type 0x00 = Control Stream
                encode_varint(0x00, &mut ctrl_buf);
                // SETTINGS frame (Type 0x04)
                let settings = vec![
                    (0x01, 0),     // QPACK max table capacity = 0 (static only)
                    (0x06, 16384), // Max field section size
                ];
                encode_udp_frame(&UdpFrame::Settings(settings), &mut ctrl_buf);
                let _ = conn.send_stream(ctrl_stream_id).write(&ctrl_buf);
                self.control_streams.insert(handle);
            }

            // Drain outgoing transmits for this connection
            self.transmit_buf.clear();
            while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
                if transmit.size > 0 {
                    let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                    outgoing.push(OutgoingDatagram {
                        peer: transmit.destination,
                        payload: packet,
                    });
                }
                self.transmit_buf.clear();
            }

            // Drain connection stream events
            while let Some(event) = conn.poll() {
                match event {
                    Event::Stream(StreamEvent::Opened { dir }) => {
                        while let Some(id) = conn.streams().accept(dir) {
                            if id.dir() == Dir::Bi {
                                Self::process_readable_stream(
                                    handle,
                                    id,
                                    conn,
                                    &mut self.stream_buffers,
                                    &mut self.stream_requests,
                                    &mut ready_requests,
                                    self.config.max_message_size,
                                );
                            }
                        }
                    }
                    Event::Stream(StreamEvent::Readable { id }) => {
                        if id.dir() == Dir::Uni {
                            if let Ok(mut chunks) = conn.recv_stream(id).read(true) {
                                while let Some(_chunk) = chunks.next(65535).ok().flatten() {}
                            }
                        } else {
                            Self::process_readable_stream(
                                handle,
                                id,
                                conn,
                                &mut self.stream_buffers,
                                &mut self.stream_requests,
                                &mut ready_requests,
                                self.config.max_message_size,
                            );
                        }
                    }
                    Event::Stream(StreamEvent::Stopped { id, .. }) => {
                        self.stream_buffers.remove(&(handle, id));
                        self.stream_requests.remove(&(handle, id));
                    }
                    Event::ConnectionLost { .. } => {
                        closed_handles.push(handle);
                    }
                    _ => {}
                }
            }

            // Drain outgoing transmits generated during event processing
            self.transmit_buf.clear();
            while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
                if transmit.size > 0 {
                    let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                    outgoing.push(OutgoingDatagram {
                        peer: transmit.destination,
                        payload: packet,
                    });
                }
                self.transmit_buf.clear();
            }
        }

        // Clean up closed connections
        for handle in closed_handles {
            self.connections.remove(&handle);
            self.control_streams.remove(&handle);
            self.stream_buffers.retain(|(h, _), _| *h != handle);
            self.stream_requests.retain(|(h, _), _| *h != handle);
        }

        (outgoing, ready_requests)
    }

    /// Reads incoming stream chunks, decodes gRPC frames, and produces complete requests.
    fn process_readable_stream(
        handle: ConnectionHandle,
        id: StreamId,
        conn: &mut Connection,
        stream_buffers: &mut HashMap<(ConnectionHandle, StreamId), BytesMut>,
        stream_requests: &mut HashMap<(ConnectionHandle, StreamId), L7Request>,
        ready_requests: &mut Vec<GrpcUdpRequestEvent>,
        max_message_size: usize,
    ) {
        let buf = stream_buffers.entry((handle, id)).or_default();
        let mut stream_finished = false;
        let mut payload_too_large = false;

        if let Ok(mut chunks) = conn.recv_stream(id).read(true) {
            loop {
                match chunks.next(65535) {
                    Ok(Some(chunk)) => {
                        if buf.len() + chunk.bytes.len() > max_message_size + 65536 {
                            payload_too_large = true;
                            break;
                        }
                        buf.extend_from_slice(&chunk.bytes);
                    }
                    Ok(None) => {
                        stream_finished = true;
                        break;
                    }
                    Err(quinn_proto::ReadError::Blocked) => break,
                    Err(quinn_proto::ReadError::Reset(_)) => {
                        stream_buffers.remove(&(handle, id));
                        stream_requests.remove(&(handle, id));
                        return;
                    }
                }
            }
            let _ = chunks.finalize();
        }

        if payload_too_large {
            let _ = conn
                .recv_stream(id)
                .stop(quinn_proto::VarInt::from_u32(0x0107)); // excessive load
            stream_buffers.remove(&(handle, id));
            stream_requests.remove(&(handle, id));
            return;
        }

        // Try decoding frames
        loop {
            match decode_udp_frame(buf) {
                Ok(Some(frame)) => match frame {
                    UdpFrame::Headers(payload) => match decode_qpack_headers(&payload) {
                        Ok(decoded) => {
                            let req = L7Request::new(
                                decoded.method.unwrap_or(http::Method::POST),
                                decoded.uri.unwrap_or_else(|| http::Uri::from_static("/")),
                                http::Version::HTTP_3,
                                decoded.headers,
                                Body::Empty,
                            );
                            stream_requests.insert((handle, id), req);
                        }
                        Err(e) => {
                            tracing::warn!(error = %e, "Failed to decode QPACK headers on gRPC UDP stream");
                            let _ = conn
                                .recv_stream(id)
                                .stop(quinn_proto::VarInt::from_u32(0x0106));
                            stream_buffers.remove(&(handle, id));
                            stream_requests.remove(&(handle, id));
                            return;
                        }
                    },
                    UdpFrame::Data(payload) => {
                        if let Some(req) = stream_requests.get_mut(&(handle, id)) {
                            match req.body {
                                Body::Empty => {
                                    req.body = Body::Bytes(payload);
                                }
                                Body::Bytes(ref existing) => {
                                    let mut merged =
                                        BytesMut::with_capacity(existing.len() + payload.len());
                                    merged.extend_from_slice(existing);
                                    merged.extend_from_slice(&payload);
                                    req.body = Body::Bytes(merged.freeze());
                                }
                            }
                        }
                    }
                    _ => {}
                },
                Ok(None) => break,
                Err(e) => {
                    tracing::warn!(error = %e, "Malformed frame on gRPC UDP stream");
                    let _ = conn
                        .recv_stream(id)
                        .stop(quinn_proto::VarInt::from_u32(0x0106));
                    stream_buffers.remove(&(handle, id));
                    stream_requests.remove(&(handle, id));
                    return;
                }
            }
        }

        // Emit request if finished or body present
        if stream_finished && let Some(request) = stream_requests.remove(&(handle, id)) {
            ready_requests.push(GrpcUdpRequestEvent {
                handle,
                stream_id: id,
                request,
            });
            stream_buffers.remove(&(handle, id));
        }
    }

    /// Serializes and sends an [`L7Response`] back on the given connection stream.
    pub fn send_response(
        &mut self,
        now: Instant,
        handle: ConnectionHandle,
        stream_id: StreamId,
        response: &L7Response,
    ) -> Result<Vec<OutgoingDatagram>, GrpcError> {
        let conn = self
            .connections
            .get_mut(&handle)
            .ok_or_else(|| GrpcError::Internal("connection handle closed".into()))?;

        // 1. Encode response HEADERS frame
        let mut header_payload = BytesMut::new();
        encode_qpack_response(response.status, &response.headers, &mut header_payload);
        let mut write_buf = BytesMut::new();
        encode_udp_frame(&UdpFrame::Headers(header_payload.freeze()), &mut write_buf);

        // 2. Encode DATA frame if body present
        if let Body::Bytes(ref b) = response.body
            && !b.is_empty()
        {
            encode_udp_frame(&UdpFrame::Data(b.clone()), &mut write_buf);
        }

        // 3. Write frames to send stream
        let mut written = 0;
        while written < write_buf.len() {
            match conn.send_stream(stream_id).write(&write_buf[written..]) {
                Ok(n) => {
                    if n == 0 {
                        break;
                    }
                    written += n;
                }
                Err(e) => return Err(GrpcError::Internal(e.to_string())),
            }
        }

        let _ = conn.send_stream(stream_id).finish();

        // 4. Drain newly generated packets
        let mut outgoing = Vec::new();
        self.transmit_buf.clear();
        while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
            if transmit.size > 0 {
                let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                outgoing.push(OutgoingDatagram {
                    peer: transmit.destination,
                    payload: packet,
                });
            }
            self.transmit_buf.clear();
        }

        Ok(outgoing)
    }

    /// Transmits a trailers-only gRPC response (e.g. for rejected RPCs or unmapped routes).
    pub fn send_trailers_only(
        &mut self,
        now: Instant,
        handle: ConnectionHandle,
        stream_id: StreamId,
        status: GrpcStatus,
        message: Option<&str>,
    ) -> Result<Vec<OutgoingDatagram>, GrpcError> {
        let resp = status.to_l7_response(message);
        self.send_response(now, handle, stream_id, &resp)
    }
}
