//! HTTP/3 packet-driven server engine based on pure quinn-proto state machine.
//!
//! Operates in a pure packet-in / packet-out manner without owning OS sockets,
//! perfectly matching `velda-transport`'s [`UdpL7Handoff`] model.

use std::collections::HashMap;
use std::net::{IpAddr, SocketAddr};
use std::sync::Arc;
use std::time::Instant;

use bytes::{Bytes, BytesMut};
use http::{HeaderMap, Method, StatusCode, Uri};
use quinn_proto::{
    Connection, ConnectionHandle, Endpoint, EndpointConfig, Event, ServerConfig, StreamEvent,
    StreamId,
};
use velda_core::{Body, L7Request, L7Response};

use crate::error::HttpError;
use crate::h3::frame::{Http3Frame, decode_frame, encode_frame};

/// An outgoing UDP packet generated by the HTTP/3 state machine.
#[derive(Debug, Clone)]
pub struct OutgoingDatagram {
    /// Destination remote address.
    pub peer: SocketAddr,
    /// Packet payload.
    pub payload: Bytes,
}

/// An incoming HTTP/3 request ready for application processing.
#[derive(Debug)]
pub struct Http3RequestEvent {
    /// Internal connection handle.
    pub handle: ConnectionHandle,
    /// QUIC bidirectional stream identifier.
    pub stream_id: StreamId,
    /// Parsed L7 request.
    pub request: L7Request,
}

/// High-performance, packet-driven HTTP/3 server engine.
pub struct Http3Engine {
    endpoint: Endpoint,
    connections: HashMap<ConnectionHandle, Connection>,
    active_peers: HashMap<SocketAddr, ConnectionHandle>,
    stream_buffers: HashMap<(ConnectionHandle, StreamId), BytesMut>,
    transmit_buf: Vec<u8>,
}

impl std::fmt::Debug for Http3Engine {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("Http3Engine")
            .field("connections", &self.connections.len())
            .finish()
    }
}

impl Http3Engine {
    /// Creates a new [`Http3Engine`] initialized with the given server configuration.
    pub fn new(server_config: Arc<ServerConfig>) -> Self {
        let endpoint_config = Arc::new(EndpointConfig::default());
        let endpoint = Endpoint::new(endpoint_config, Some(server_config), false, None);
        Self {
            endpoint,
            connections: HashMap::new(),
            active_peers: HashMap::new(),
            stream_buffers: HashMap::new(),
            transmit_buf: vec![0u8; 65535],
        }
    }

    /// Ingests an incoming UDP datagram payload, advances the QUIC state machine,
    /// and returns any outgoing UDP packets and complete HTTP/3 requests.
    pub fn handle_datagram(
        &mut self,
        now: Instant,
        remote: SocketAddr,
        local_ip: Option<IpAddr>,
        data: &[u8],
    ) -> (Vec<OutgoingDatagram>, Vec<Http3RequestEvent>) {
        let mut outgoing = Vec::new();
        let mut ready_requests = Vec::new();

        let mut resp_buf = Vec::new();
        let bytes_mut = BytesMut::from(data);

        // 1. Ingest datagram into endpoint
        let event = self
            .endpoint
            .handle(now, remote, local_ip, None, bytes_mut, &mut resp_buf);

        if !resp_buf.is_empty() {
            outgoing.push(OutgoingDatagram {
                peer: remote,
                payload: Bytes::from(resp_buf),
            });
        }

        // 2. Handle connection events
        if let Some(event) = event {
            match event {
                quinn_proto::DatagramEvent::NewConnection(incoming) => {
                    let mut accept_resp = Vec::new();
                    if let Ok((handle, conn)) =
                        self.endpoint.accept(incoming, now, &mut accept_resp, None)
                    {
                        if !accept_resp.is_empty() {
                            outgoing.push(OutgoingDatagram {
                                peer: remote,
                                payload: Bytes::from(accept_resp),
                            });
                        }
                        self.connections.insert(handle, conn);
                        self.active_peers.insert(remote, handle);
                    }
                }
                quinn_proto::DatagramEvent::ConnectionEvent(handle, ev) => {
                    if let Some(conn) = self.connections.get_mut(&handle) {
                        conn.handle_event(ev);
                    }
                }
                quinn_proto::DatagramEvent::Response(transmit) => {
                    if transmit.size > 0 {
                        // Handled via transmit_buf if needed
                    }
                }
            }
        }

        // 3. Poll connection events & read streams across connections
        let mut closed_handles = Vec::new();

        for (&handle, conn) in self.connections.iter_mut() {
            // Drain outgoing transmits for this connection
            while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
                if transmit.size > 0 {
                    let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                    outgoing.push(OutgoingDatagram {
                        peer: transmit.destination,
                        payload: packet,
                    });
                }
            }

            // Drain connection events
            while let Some(event) = conn.poll() {
                match event {
                    Event::Stream(StreamEvent::Readable { id }) => {
                        let buf = self.stream_buffers.entry((handle, id)).or_default();

                        if let Ok(mut chunks) = conn.recv_stream(id).read(true) {
                            while let Some(chunk) = chunks.next(65535).ok().flatten() {
                                buf.extend_from_slice(&chunk.bytes);
                            }
                        }

                        // Try decoding HTTP/3 frames
                        while let Ok(Some(frame)) = decode_frame(buf) {
                            match frame {
                                Http3Frame::Headers(payload) => {
                                    // Parse standard HTTP/3 pseudo headers or minimal payload
                                    let req = parse_h3_request(payload);
                                    ready_requests.push(Http3RequestEvent {
                                        handle,
                                        stream_id: id,
                                        request: req,
                                    });
                                }
                                Http3Frame::Data(payload) => {
                                    // Append data chunks if request already in flight
                                    let _ = payload;
                                }
                                _ => {}
                            }
                        }
                    }
                    Event::ConnectionLost { .. } => {
                        closed_handles.push(handle);
                    }
                    _ => {}
                }
            }
        }

        // Clean up closed connections
        for handle in closed_handles {
            self.connections.remove(&handle);
            self.stream_buffers.retain(|(h, _), _| *h != handle);
        }

        (outgoing, ready_requests)
    }

    /// Serializes an [`L7Response`] into HTTP/3 frames and queues them on the specified stream.
    pub fn send_response(
        &mut self,
        now: Instant,
        handle: ConnectionHandle,
        stream_id: StreamId,
        response: &L7Response,
    ) -> Result<Vec<OutgoingDatagram>, HttpError> {
        let conn = self
            .connections
            .get_mut(&handle)
            .ok_or_else(|| HttpError::H3("Connection not found".into()))?;

        // 1. Encode HEADERS frame
        let mut header_payload = BytesMut::new();
        encode_minimal_headers(response.status, &mut header_payload);
        let header_frame = Http3Frame::Headers(header_payload.freeze());

        let mut write_buf = BytesMut::new();
        encode_frame(&header_frame, &mut write_buf);

        // 2. Encode DATA frame if body present
        if let Body::Bytes(ref b) = response.body {
            let data_frame = Http3Frame::Data(b.clone());
            encode_frame(&data_frame, &mut write_buf);
        }

        // Write frames to send stream
        conn.send_stream(stream_id)
            .write(&write_buf)
            .map_err(|e| HttpError::H3(e.to_string()))?;

        // Finish stream
        let _ = conn.send_stream(stream_id).finish();

        // 3. Drain newly generated packets
        let mut outgoing = Vec::new();
        while let Some(transmit) = conn.poll_transmit(now, 1, &mut self.transmit_buf) {
            if transmit.size > 0 {
                let packet = Bytes::copy_from_slice(&self.transmit_buf[..transmit.size]);
                outgoing.push(OutgoingDatagram {
                    peer: transmit.destination,
                    payload: packet,
                });
            }
        }

        Ok(outgoing)
    }

    /// Returns the number of currently active connections.
    #[inline]
    pub fn connection_count(&self) -> usize {
        self.connections.len()
    }
}

/// Helper parsing minimal HTTP/3 request payload into [`L7Request`].
fn parse_h3_request(payload: Bytes) -> L7Request {
    // If payload contains text-encoded or basic header fields
    let mut method = Method::GET;
    let mut uri = Uri::from_static("/");
    let headers = HeaderMap::new();

    // Check if raw payload starts with simple ascii or method bytes
    if let Ok(s) = std::str::from_utf8(&payload) {
        let parts: Vec<&str> = s.split_whitespace().collect();
        if parts.len() >= 2 {
            if let Ok(m) = Method::from_bytes(parts[0].as_bytes()) {
                method = m;
            }
            if let Ok(u) = parts[1].parse::<Uri>() {
                uri = u;
            }
        }
    }

    L7Request::new(method, uri, http::Version::HTTP_3, headers, Body::Empty)
}

/// Helper encoding minimal HTTP/3 response headers.
fn encode_minimal_headers(status: StatusCode, dst: &mut BytesMut) {
    let status_str = format!(":status {}", status.as_u16());
    dst.extend_from_slice(status_str.as_bytes());
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_h3_request() {
        let payload = Bytes::from_static(b"GET /api/v1/test HTTP/3");
        let req = parse_h3_request(payload);
        assert_eq!(req.method, Method::GET);
        assert_eq!(req.path(), "/api/v1/test");
        assert_eq!(req.version, http::Version::HTTP_3);
    }

    #[test]
    fn test_http3_engine_lifecycle_and_datagram() {
        let cert = rcgen::generate_simple_self_signed(vec!["localhost".into()]).unwrap();
        let cert_der = cert.cert.der().to_vec();
        let key_der = cert.signing_key.serialize_der();

        let cert_chain = vec![rustls::pki_types::CertificateDer::from(cert_der)];
        let private_key = rustls::pki_types::PrivateKeyDer::Pkcs8(
            rustls::pki_types::PrivatePkcs8KeyDer::from(key_der),
        );

        let mut rustls_server = rustls::ServerConfig::builder()
            .with_no_client_auth()
            .with_single_cert(cert_chain, private_key)
            .unwrap();
        rustls_server.alpn_protocols = vec![b"h3".to_vec()];
        let quic_crypto =
            quinn_proto::crypto::rustls::QuicServerConfig::try_from(Arc::new(rustls_server))
                .unwrap();
        let server_config = ServerConfig::with_crypto(Arc::new(quic_crypto));
        let mut engine = Http3Engine::new(Arc::new(server_config));

        assert_eq!(engine.connection_count(), 0);

        let peer: SocketAddr = "127.0.0.1:45678".parse().unwrap();
        let (outgoing, requests) =
            engine.handle_datagram(Instant::now(), peer, None, b"invalid-quic-packet");

        // Invalid packet is rejected without panic
        assert_eq!(requests.len(), 0);
        let _ = outgoing;
    }
}
