[package]
name = "velda-http3"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
velda-core = { path = "../velda-core" }
tokio = { version = "1.43", features = ["io-util", "sync", "macros", "rt", "net"] }
bytes = "1.10"
http = "1.2"
thiserror = "2.0"
tracing = "0.1"
quinn-proto = { version = "0.11", default-features = false, features = ["rustls"] }

[dev-dependencies]
tokio = { version = "1.43", features = ["full"] }
rcgen = "0.14.10"
rustls = { version = "0.23", default-features = false, features = ["ring", "std"] }
